changelog:
  categories:
    - labels: [breaking]
      title: Breaking changes
    - labels: [bug]
      title: Fixes
    - labels: [enhancement]
      title: New
    - labels: [documentation]
      title: Documentation
    - labels: ["*"]
      title: Other changes
  exclude:
    labels: [dependencies, maintenance]
