external_components:
  - components: [scheduler]
    source:
      path: .
      ref: ${version}
      type: git
      url: https://github.com/zygimantas/esphome-tesla-ble-scheduler

packages:
  device: github://zygimantas/esphome-tesla-ble-scheduler/device.yaml@${version}

substitutions:
  version: v5.7.0
